In [2]:
import pandas as pd
df = pd.read_csv("/content/supply_chain_dataset1.csv")
df.head()

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

In [3]:
df.info()
df.duplicated().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91250 entries, 0 to 91249
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     91250 non-null  object
 1   SKU_ID                   91250 non-null  object
 2   Warehouse_ID             91250 non-null  object
 3   Supplier_ID              91250 non-null  object
 4   Region                   91250 non-null  object
 5   Units_Sold               91250 non-null  int64
 6   Inventory_Level          91250 non-null  int64
 7   Supplier_Lead_Time_Days  91250 non-null  int64
 8   Reorder_Point            91250 non-null  int64
 9   Order_Quantity           91250 non-null  int64
 10  Unit_Cost                91250 non-null  float64
 11  Unit_Price               91250 non-null  float64
 12  Promotion_Flag           91250 non-null  int64
 13  Stockout_Flag            91250 non-null  int64
 14  Demand_Forecast          91250 non-null  float64
dtypes: float64(3), int64(7), object(5)
memory usage: 10.4+ MB

,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
count,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.0,91250.000000
mean,20.054564,471.522312,7.984000,300.068000,19.272493,12.203320,18.261800,0.101589,0.0,20.082033
std,9.068602,133.488002,3.907929,54.879945,82.340831,4.574982,7.121136,0.302109,0.0,9.503955
min,0.000000,168.000000,2.000000,201.000000,0.000000,5.020000,6.950000,0.000000,0.0,0.000000
25%,13.000000,370.000000,4.000000,252.000000,0.000000,8.180000,12.000000,0.000000,0.0,12.950000
50%,20.000000,461.000000,8.000000,300.000000,0.000000,11.990000,18.180000,0.000000,0.0,19.950000
75%,27.000000,564.000000,11.000000,346.000000,0.000000,16.320000,23.390000,0.000000,0.0,26.930000
max,59.000000,990.000000,14.000000,398.000000,499.000000,19.760000,35.100000,1.000000,0.0,61.420000

In [4]:
print("SKU:", df['SKU_ID'].nunique())
print("Warehouse:", df['Warehouse_ID'].nunique())
print("Supplier:", df['Supplier_ID'].nunique())
print("Region:", df['Region'].nunique())

for col in ['SKU_ID', 'Warehouse_ID', 'Supplier_ID', 'Region']:
    print(f"\n{col}:")
    print(df[col].unique())

SKU: 50
Warehouse: 5
Supplier: 10
Region: 4

SKU_ID:
['SKU_1' 'SKU_2' 'SKU_3' 'SKU_4' 'SKU_5' 'SKU_6' 'SKU_7' 'SKU_8' 'SKU_9'
 'SKU_10' 'SKU_11' 'SKU_12' 'SKU_13' 'SKU_14' 'SKU_15' 'SKU_16' 'SKU_17'
 'SKU_18' 'SKU_19' 'SKU_20' 'SKU_21' 'SKU_22' 'SKU_23' 'SKU_24' 'SKU_25'
 'SKU_26' 'SKU_27' 'SKU_28' 'SKU_29' 'SKU_30' 'SKU_31' 'SKU_32' 'SKU_33'
 'SKU_34' 'SKU_35' 'SKU_36' 'SKU_37' 'SKU_38' 'SKU_39' 'SKU_40' 'SKU_41'
 'SKU_42' 'SKU_43' 'SKU_44' 'SKU_45' 'SKU_46' 'SKU_47' 'SKU_48' 'SKU_49'
 'SKU_50']

Warehouse_ID:
['WH_1' 'WH_2' 'WH_3' 'WH_4' 'WH_5']

Supplier_ID:
['SUP_8' 'SUP_5' 'SUP_9' 'SUP_2' 'SUP_7' 'SUP_10' 'SUP_6' 'SUP_4' 'SUP_3'
 'SUP_1']

Region:
['West' 'North' 'South' 'East']

In [5]:
numeric_cols = [
    'Units_Sold',
    'Inventory_Level',
    'Supplier_Lead_Time_Days',
    'Reorder_Point',
    'Order_Quantity',
    'Unit_Cost',
    'Unit_Price',
    'Promotion_Flag',
    'Stockout_Flag',
    'Demand_Forecast'
]

for col in numeric_cols:
    print(f"\n{col}")
    print(df[col].describe())

Units_Sold
count    91250.000000
mean        20.054564
std          9.068602
min          0.000000
25%         13.000000
50%         20.000000
75%         27.000000
max         59.000000
Name: Units_Sold, dtype: float64

Inventory_Level
count    91250.000000
mean       471.522312
std        133.488002
min        168.000000
25%        370.000000
50%        461.000000
75%        564.000000
max        990.000000
Name: Inventory_Level, dtype: float64

Supplier_Lead_Time_Days
count    91250.000000
mean         7.984000
std          3.907929
min          2.000000
25%          4.000000
50%          8.000000
75%         11.000000
max         14.000000
Name: Supplier_Lead_Time_Days, dtype: float64

Reorder_Point
count    91250.000000
mean       300.068000
std         54.879945
min        201.000000
25%        252.000000
50%        300.000000
75%        346.000000
max        398.000000
Name: Reorder_Point, dtype: float64

Order_Quantity
count    91250.000000
mean        19.272493
std         82.340831
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        499.000000
Name: Order_Quantity, dtype: float64

Unit_Cost
count    91250.000000
mean        12.203320
std          4.574982
min          5.020000
25%          8.180000
50%         11.990000
75%         16.320000
max         19.760000
Name: Unit_Cost, dtype: float64

Unit_Price
count    91250.000000
mean        18.261800
std          7.121136
min          6.950000
25%         12.000000
50%         18.180000
75%         23.390000
max         35.100000
Name: Unit_Price, dtype: float64

Promotion_Flag
count    91250.000000
mean         0.101589
std          0.302109
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Promotion_Flag, dtype: float64

Stockout_Flag
count    91250.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: Stockout_Flag, dtype: float64

Demand_Forecast
count    91250.000000
mean        20.082033
std          9.503955
min          0.000000
25%         12.950000
50%         19.950000
75%         26.930000
max         61.420000
Name: Demand_Forecast, dtype: float64

In [6]:
for col in numeric_cols:
    print(col, ":", (df[col] < 0).sum())

Units_Sold : 0
Inventory_Level : 0
Supplier_Lead_Time_Days : 0
Reorder_Point : 0
Order_Quantity : 0
Unit_Cost : 0
Unit_Price : 0
Promotion_Flag : 0
Stockout_Flag : 0
Demand_Forecast : 0

In [7]:
# Period
print("Tanggal awal :", df['Date'].min())
print("Tanggal akhir:", df['Date'].max())

Tanggal awal : 2024-01-01
Tanggal akhir: 2024-12-30